In [1]:
my_file = open("numbers.txt", "a")
my_file.write("3, 45, 83, 21")
my_file.close()

In [22]:
percentage=int(input("what is your percentage mark, select from 0 to 100"))
def mark_done():
    if 90<= percentage <=100:
        print("you have got an A+ grad")
        return "grade A+"
    elif 80<= percentage <=89 :
        print ("this is grade A")
        return "Grade A"
    elif 70<= percentage <=79 :
        print ("this is grade B")
        return "Grade B"
    elif 60<= percentage <=69 :
        print ("this is grade C")
        return "Grade C"
    elif 50<= percentage <=59 :
        print ("this is grade D")
        return "Grade D"
    else:
        print ("this is grade F")
        return "Grade F"



mark_done()
message= mark_done()
print(type(message))

target_grade=input("what is your target grade")
print("this is your targe grade", target_grade, "and this is your actual grade", message)
def comparegrade():
    if target_grade==message:
        print("you have made your target grade")
    elif target_grade>message:
        print("you are great")
    elif target_grade<message:
        print(" you have not done it")


comparegrade()

    







#target_grade=input("what is your target grade")





this is grade B
this is grade B
<class 'str'>
this is your targe grade A and this is your actual grade Grade B
you are great


In [26]:
import numpy as np
one_array=np.arange(10)
print(one_array)
print(one_array.size)
print(len(one_array))


[0 1 2 3 4 5 6 7 8 9]
10
10


In [29]:
three_dey=np.ones(9)
print(three_dey)
newarray=three_dey.reshape(3,3)
print(newarray)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
oneto10=np.array([1,2,3,4,5,6,7,8,9,10])
# to find columns
oneto10[0:9:2]

array([1, 3, 5, 7, 9])

In [37]:
oneto10=np.array([1,2,3,4,5,6,7,8,9,10])
# to find columns
oneto10[0:9:2]=(-1)
print(oneto10)


[-1  2 -1  4 -1  6 -1  8 -1 10]


In [39]:
oneto10=np.array([1,2,3,4,5,6,7,8,9,10])
oneto10.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [69]:
oneto10=np.arange(1,10).reshape(3,3)
print(oneto10)
print(oneto10.ndim)

secondarray=np.arange(7,16).reshape(3,3)
print(secondarray)
print(secondarray.ndim)
c=np.dot(oneto10,secondarray)
print("this is dot answer")
print(c)

e = np.sum(c,axis = 1)
print("this is sum answer")
print(e)
#



[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]
2
this is dot answer
[[ 66  72  78]
 [156 171 186]
 [246 270 294]]
this is sum answer
[216 513 810]


In [81]:
usingone=np.ones(3)
usingtwo=np.ones(3) *2
usingthree=np.ones(3) *3
print(usingone)
print(usingtwo)
print(usingthree)
combine=np.array([usingone,usingtwo,usingthree])
print(combine)

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [97]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8,9])
print(b[0])
print("array a=",a)
print("array b=",b)
d=np.array([1])
e=np.array([2])
filter_arr=[]
for element in a:
  # if the element is equal to b, dont append
  if element == b[0]:
    filter_arr.append(False)
  else:
    filter_arr.append(True)

newarr = d[filter_arr]

print(filter_arr)
print(newarr)





4
array a= [1 2 3 4 5]
array b= [4 5 6 7 8 9]


IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 5

In [91]:

a1 = np.array([1,2,4,6,7])
a2 = np.array([1,3,4,5,7])
a3 = np.array([1,3,4.00001,5,7])

print((a1==a2).all())
print((a3==a2).all())

False
False


items 3 to 7: [4 5 6 7],  SUM IS : 22


select a if you want to add 
    "b if you want to subtract,
    "c if you want to divide
    "d if you want to multiply
    "e if you want to square
a
7


select a if you want to add 
"b if you want to subtract,
"c if you want to divide
"d if you want to multiply
"e if you want to square
b
-1
i am here
